In [26]:
import numpy as np

In [67]:
crop_data = np.genfromtxt('Datasets/Crop_recommendation.txt', delimiter=',', skip_header=1)

In [68]:
crop_data[0]

array([ 90.        ,  42.        ,  43.        ,  20.87974371,
        82.00274423,   6.50298529, 202.9355362 ,          nan])

In [69]:
# Deleting the columns
crop_data = np.delete(crop_data, [0,1,2,5], axis=1)

In [70]:
crop_data

array([[ 20.87974371,  82.00274423, 202.9355362 ,          nan],
       [ 21.77046169,  80.31964408, 226.6555374 ,          nan],
       [ 23.00445915,  82.3207629 , 263.9642476 ,          nan],
       ...,
       [ 24.13179691,  67.22512329, 173.3228386 ,          nan],
       [ 26.2724184 ,  52.12739421, 127.1752928 ,          nan],
       [ 23.60301571,  60.39647474, 140.9370415 ,          nan]])

In [71]:
np.isnan(crop_data)

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       ...,
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [73]:
# Clean nan values
crop_data = crop_data[:,~np.isnan(crop_data).any(axis=0)]

In [75]:
crop_data

array([[ 20.87974371,  82.00274423, 202.9355362 ],
       [ 21.77046169,  80.31964408, 226.6555374 ],
       [ 23.00445915,  82.3207629 , 263.9642476 ],
       ...,
       [ 24.13179691,  67.22512329, 173.3228386 ],
       [ 26.2724184 ,  52.12739421, 127.1752928 ],
       [ 23.60301571,  60.39647474, 140.9370415 ]])

In [76]:
crop_data.shape

(2200, 3)

In [77]:
weights = np.array([0.3,1.2,.8])

In [78]:
yields = np.matmul(crop_data,weights)

In [79]:
yields

array([267.01564515, 284.23914132, 316.8576513 , ..., 226.5679579 ,
       172.17483281, 192.3063076 ])

## Now we add these `yield` data to the `crop_data` array

In [80]:
yields.shape

(2200,)

In [90]:
yields = yields.reshape(2200,1)

In [91]:
crop_data.shape

(2200, 3)

In [92]:
yields.shape

(2200, 1)

We have converted the `yields` to 2D array \n
let concatinate `crop_data` with `yields` \n
`axis=1` means concatinate the column. \n

In [93]:
crop_data = np.concatenate((crop_data, yields), axis=1)

In [94]:
crop_data

array([[ 20.87974371,  82.00274423, 202.9355362 , 267.01564515],
       [ 21.77046169,  80.31964408, 226.6555374 , 284.23914132],
       [ 23.00445915,  82.3207629 , 263.9642476 , 316.8576513 ],
       ...,
       [ 24.13179691,  67.22512329, 173.3228386 , 226.5679579 ],
       [ 26.2724184 ,  52.12739421, 127.1752928 , 172.17483281],
       [ 23.60301571,  60.39647474, 140.9370415 , 192.3063076 ]])

## Let save the `crop_data` in a `apple_yield.txt` file

In [96]:
np.savetxt('Datasets/apple_yield.txt',
           crop_data,
          fmt = '%.2f',
          header = 'temperature,humidity,rainfall,apple_yield',
          comments = '')