# Dot product using numpy.

In [1]:
import numpy as np

In [2]:
x = [73,56,81]
weights = [0.3,1.2,0.8]

In [3]:
for x, w in zip(x, weights):
    result = 0
    result += x * w
result

64.8

In [ ]:
# Now using dot product function
help(np.dot)

In [4]:
x = np.array(x)
weights = np.array(weights)
result = np.dot(x ,weights)
result

array([24.3, 97.2, 64.8])

## Benifits of numpy

In [20]:
values = list(range(1000000))
weights = list(range(1000000,2000000))

In [21]:
%%time
for x, y in zip(values, weights):
    result = 0
    result += x * y
result

CPU times: total: 125 ms
Wall time: 325 ms


1999997000001

In [22]:
np_arr1 = np.array(values, dtype=np.int64)
np_arr2 = np.array(weights, dtype=np.int64)

In [23]:
np.dtype(np_arr2[0])

dtype('int64')

In [24]:
%%time
np.dot(np_arr1, np_arr2)

CPU times: total: 0 ns
Wall time: 0 ns


833332333333500000

## 2D Arrays

In [38]:
climate = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int64)
weights = np.array([0.3,1.2,0.8], dtype=np.float64)

In [39]:
climate

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [40]:
climate.dtype

dtype('int64')

In [41]:
result = 0
for x in climate:
    result += np.dot(x,weights)
result

36.0

In [47]:
result = []
for cl in climate:
    individual = 0
    for x, w in zip(cl, weights):
        individual += x * w
    result.append(individual)
result

[5.1, 12.0, 18.9]

## Matrics Multiplication  
### np.matmul()

In [43]:
climate

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [44]:
weights

array([0.3, 1.2, 0.8])

In [45]:
np.matmul(climate,weights)

array([ 5.1, 12. , 18.9])

In [48]:
climate @ weights

array([ 5.1, 12. , 18.9])