In [1]:
import numpy as np

In [2]:
arr = np.array([
    
    [[1,2,3,4],
     [5,6,7,8]],
    
    [[9,10,11,12],
     [13,14,15,16]],
    
    [[17,18,19,20],
     [21,21,23,24]],
    
    ])

In [4]:
arr.shape

(3, 2, 4)

## Arithmatic operation

In [5]:
arr + 2

array([[[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]],

       [[19, 20, 21, 22],
        [23, 23, 25, 26]]])

In [7]:
arr - 2

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[18, 20, 22, 24],
        [26, 28, 30, 32]],

       [[34, 36, 38, 40],
        [42, 42, 46, 48]]])

In [10]:
arr * arr

array([[[  1,   4,   9,  16],
        [ 25,  36,  49,  64]],

       [[ 81, 100, 121, 144],
        [169, 196, 225, 256]],

       [[289, 324, 361, 400],
        [441, 441, 529, 576]]])

In [11]:
arr / arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## Logical operation

In [14]:
arr_1 = np.array([
    
    [[1,2,3,4],
     [5,6,7,8]],
    
    [[9,10,11,12],
     [13,14,15,16]],
    
    [[17,18,19,20],
     [21,21,23,24]],
    
    ])

arr_2 = np.array([
    
    [[1,2,3,4],
     [5,6,9,8]],
    
    [[9,10,1,12],
     [13,14,15,16]],
    
    [[17,8,19,20],
     [21,21,2,24]],
    
    ])

In [16]:
arr_1 == arr_2

array([[[ True,  True,  True,  True],
        [ True,  True, False,  True]],

       [[ True,  True, False,  True],
        [ True,  True,  True,  True]],

       [[ True, False,  True,  True],
        [ True,  True, False,  True]]])

In [19]:
arr > arr_2

array([[[ True,  True,  True,  True],
        [ True,  True, False,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [20]:
arr.dtype

dtype('int32')

In [21]:
(arr == arr_1).dtype

dtype('bool')

In [23]:
(arr_1 == arr_2).sum()

20

## Slicing

In [28]:
arr = np.array([
    
    [[1,2,3,4],
     [5,6,7,8]],
    
    [[9,10,11,12],
     [13,14,15,16]],
    
    [[17,18,19,20],
     [21,22,23,24]],
    
    ])

In [29]:
# print from 9 to 16
arr[1:2]

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [34]:
arr[1:2].shape

(1, 2, 4)

In [30]:
# print value : 23
arr[2,1,2]

23

In [35]:
arr[2,1,2].shape

()

In [31]:
# print 6,7 14,15 22,23
arr[:,1:,1:3]

array([[[ 6,  7]],

       [[14, 15]],

       [[22, 23]]])

In [32]:
arr[1: , : , :3]

array([[[ 9, 10, 11],
        [13, 14, 15]],

       [[17, 18, 19],
        [21, 22, 23]]])

In [33]:
arr[1:, 1, :3]

array([[13, 14, 15],
       [21, 22, 23]])

In [36]:
arr[1:, 1, :3].shape

(2, 3)

In [37]:
arr[:,1:,3]

array([[ 8],
       [16],
       [24]])

In [38]:
arr[:,1:,3].shape

(3, 1)

In [39]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [41]:
arr[:2 , 1 , :3:2]

array([[ 5,  7],
       [13, 15]])

In [43]:
arr[::2 , : ,::2]

array([[[ 1,  3],
        [ 5,  7]],

       [[17, 19],
        [21, 23]]])

## Different ways to create arrays

In [55]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.eye(5,5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.random.rand(5)

array([0.41005214, 0.69383862, 0.53563094, 0.36618922, 0.38099589])

In [54]:
np.random.randn(5)

array([-0.85985342, -1.97065045, -0.83808221,  0.12620066, -0.53579434])

In [62]:
np.full((3,4),53)

array([[53, 53, 53, 53],
       [53, 53, 53, 53],
       [53, 53, 53, 53]])

In [65]:
np.arange(11,101)

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [68]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [83]:
np.arange(1,151).reshape(6,5,5)

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125]],

       [[126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140],
        [1

In [86]:
np.arange(1,151).reshape(6,5,-1)

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125]],

       [[126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140],
        [1

In [91]:
np.arange(1,100).reshape(3,3,-1) # one dimension will be calculate by itself.

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]],

       [[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]],

       [[67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [94]:
np.linspace(11,101,10) #give no. of elements from range.

array([ 11.,  21.,  31.,  41.,  51.,  61.,  71.,  81.,  91., 101.])

In [95]:
np.linspace(12,15,6)

array([12. , 12.6, 13.2, 13.8, 14.4, 15. ])